### ISSUE TITLE
Fix LLIN_given in BA ANC health facility visit task

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#128]
Leftover from this issue: https://github.com/OpenSRP/opensrp-client-chw-anc/issues/23

- [x] The field LLIN_given appears for all ANC health facility visits but it should only appear for the first one, is not addressed yet.

**Comment by msschroeder** [comment]
QA July 17th Build:

- [ ] This question still appear for all HH visits. It seems to be related to the HF task not working either. It does not appear to be incrementing up after one home visit.

**Comment by rkodev** [comment]
@msschroeder when testing this issue and you adjust the dates on the testing device, you can manually sync the events using the sync button on the navigation menu before opening a new visit. This will force the events to be processed again since home visits are not processed until 24hrs lapse after submission to allow for editing

**Comment by rkodev** [comment]
- Resolved

**Comment by msschroeder** [comment]
lgtm
