### ISSUE TITLE
IPTp-SP dose and ANC health facility visit repeat in next ANC visit

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#152]
ANC health facility visit and IPTp-SP dose are repeated in the next home visit.

To replicate:
- Add a new ANC record (make her at least 13 weeks gest. age)
- Record a home visit and record IPTp-SP dose 1 (today's date) as well as ANC health facility visit 1
- Submit the home visit
- Change the device date/time settings to 4 weeks in the future
- Record another home visit for the woman. You'll see that the IPTp-SP dose 1 is showing again, as well as the first ANC health facility visit, even though they were marked as given in the last home visit.

**Comment by rkodev** [comment]
@cafootitt when testing this issue and you adjust the dates on the testing device, you can manually sync the events using the sync button on the navigation menu before opening a new visit. This will force the events to be processed again since home visits are not processed until 24hrs lapse after submission to allow for editing.

**Comment by rkodev** [comment]
- Resolved

**Comment by cafootitt** [comment]
IPTp-SP and TT doses are still repeating in the next home visit. I'm creating a new issue and closing this one.
