### ISSUE TITLE
Discussion: How do we handle multiple babies?

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-anc#158]
How will the PNC register handle multiple Babies?

### Entering data
Currently, in the pregnancy outcome form, there is only space to enter information for 1 baby. How would multiple babies be handled?

Maybe we could allow the pregnancy outcome form to be filled multiple time.

### PNC profile page for a mother of multiple children
How will a PNC profile page appear for a mother with multiple children?

We could just display the second child after the first child in the profile page for 0 -28 days (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/78). 

### Editing info for multiple children
How will the drop down for a mother with multiple children appear on her profile page?

We could just add another Edit Child under 5 row in the drop down.

**Comment by rowo** [comment]
First, it would be helpful to research other solutions in the market to see how they deal with this. For how it appears in the app, I think the main question is what is possible technically — would it still be one PNC visit task or does it need to be two? Are the forms structured so there's a clear break point for answering questions for child 1, 2, 3, etc?

**Comment by msschroeder** [comment]
After a discussion with Carolyn. The workaround is to create one child with the pregnancy outcome form and the other child from the register a child under 5 year from the family profile. We will address this more once the PNC module has been developed

**Comment by cafootitt** [comment]
Thanks Megan, and just to add to this. Due to timelines, I don't see us being able to scope, design, and implement this ahead of our August deadlines, but it is an important use case that we will need to support and implement a solution for, so we can still be discussing the solution, but I don't think we'll get it in in time for August.

**Comment by cafootitt** [comment]
Picking this up again, as we'll need to implement this pretty soon. Here's a potential way to address this issue, with some questions that I still have inline:

1. In the pregnancy outcome form, if they select outcome of live birth, we will need to ask a question about how many babies were born, then if more than one, then we need to sub-divide the Baby section of the form into sub-sections for each baby. We'd need to label the sub-sections as Baby 1 Details, Baby 2 Details, etc.
2. On the profile page for PNC, we'll need to add the details of the other babies in the top demographic section. We can just add additional rows underneath the avatar for each additional baby.
3. If the babies are different sex, then we can either show the first baby's gender as the color around the avatar, or we can mix the color, so one side of the circle is blue, one side is pink. etc.
4. In the PNC home visit, we'll need to append the child's name to the baby tasks (we are already doing this). 
Question: Do we separate baby 1 tasks from baby 2 tasks, or do we sort the same tasks together:

Option 1:
- Breastfeeding - Baby 1
- Umbilical cord care - Baby 1
- Breastfeeding - Baby 2
- Umbilical cord care - Baby 2

Option 2:
- Breastfeeding - Baby 1
- Breastfeeding - Baby 2
- Umbilical cord care - Baby 1
- Umbilical cord care - Baby 2

If I was a CHW, I think I'd prefer Option 1. Smaller chance of mixing them up.

5. We'll need a way to separate Baby 1 from Baby 2 details in the Upcoming services and Medical History pages.
6. Do we combine both children into the "Edit Child Under 5" form in the top right dropdown menu, or do we separate them into two different forms, so "Edit Child Under 5 - Baby 1" and "Edit Child Under 5 - Baby 2"?

**Comment by msschroeder** [comment]
@rowo @cafootitt @mberg @manutarus @rkodev 

I agree with points 1 -3.

For point 4, I also agree that we should use Option 1:

Option 1:

Breastfeeding - Baby 1
Umbilical cord care - Baby 1
Breastfeeding - Baby 2
Umbilical cord care - Baby 2

I agree with point 5

__Do we combine both children into the "Edit Child Under 5" form in the top right dropdown menu, or do we separate them into two different forms, so "Edit Child Under 5 - Baby 1" and "Edit Child Under 5 - Baby 2"?__
@manutarus Do you have any technical insights that you might be able to provide to help us understand the technical implications for which way? Is there one way that is easier? Is one way take significantly more LOE than the other?

**Comment by cafootitt** [comment]
Moving a discussion from Slack over to this discussion Github issue.

For no. 1 above, agreement seems to be to use a repeating group, which is already supported in native forms. Folks can check out the sample app for repeating group [here](https://github.com/OpenSRP/opensrp-client-native-form#repeating-group).

The only concern is that there are too many fields for each child, which makes the user have to scroll to see the 2nd repeating group, so @rowo 's suggestion is to include an additional line of text at the start of the first repeating group containing instructions, e.g. "fill out information for each child". Roger, if this is not easy to do (which I imagine it might not be, since that would render the first repeat group different from the subsequent ones; plus the alternative of putting the note above the first repeat group might cause confusion if it appears before the repeated groups appear), are you still ok using the repeat group as is for now (i.e. sans instruction note)?

To move forward on this, @rowo would you be able to provide a mockup showing numbers 2-3, and 5-6 in [this comment](https://github.com/OpenSRP/opensrp-client-chw-anc/issues/158#issuecomment-533996429)? Are you ok with the approach described for all 1-6?

**Comment by msschroeder** [comment]
@cafootitt @rowo What if we did a note before the baby details or after the question of how many children with such information like "Fill out information for each child". Then, with each child you could also consider "Fill out the information for child [1-n]".

**Comment by cafootitt** [comment]
Yea, I think we can look at the different options during implementation.

**Comment by msschroeder** [comment]
@rowo @cafootitt I think we are ready to move this implementation?

**Comment by cafootitt** [comment]
Waiting for mockups from @rowo. See this comment: https://github.com/OpenSRP/opensrp-client-chw-anc/issues/158#issuecomment-545421014

**Comment by msschroeder** [comment]
Cool.

**Comment by rowo** [comment]
So in PNC, did y'all decide against showing 2+ separate PNCs for 2+ children?

**Comment by cafootitt** [comment]
Hm, I don't know if we discussed that option. 

Just thinking quickly here, and assuming you mean two separate PNC profiles(?), which PNC profile would we include the mother's PNC tasks in? Is there a chance that the user wouldn't know to locate the other PNC profile to complete the tasks for the other child?

What are the advantages of separating the profiles?

**Comment by rowo** [comment]
@cafootitt @msschroeder Separating out the profiles means we don't have to build any new functionality to build a single PNC profile that can handle N number of children. We could treat all children the same. It would be much clearer who's record you were updating and to treat everybody as individuals. 

Also, this led me to think the mom should also have her own PNC record. If the user knows they should locate one person's profile, I think we can make it clear each person has their own record. Really, having a combined profile would be the confusing part. If the workflow is that mom and child are in PNC after delivery, and they are present in front of you (the user), doesn't seem like it'd be confusing.

**Comment by rowo** [comment]
@cafootitt @msschroeder @rkodev 

@mberg had some thoughts and brought up some points supporting separating out into separate profiles. Individual profiles for mother and child(ren) immediately after birth:
- are less messy in terms of showing questions
- are less work (if we don't have to build a special PNC profile that can support one or more children)
- are more consistent (follows how profiles work in rest of OpenSRP)
- can support if a child isn't present
- are clearer to know who you are updating or editing

I know it's late so on top of thinking about desirability, we have to consider feasibility.

**Comment by cafootitt** [comment]
Ok, I see the advantages here. Here are my concerns, though:

1) The entire module is finished at this stage (just addressing bug fixes), and live data is being collected in the field already. This sounds like a big shift in the data model (not sure though). Would this have any impact on data already collected? Would a data migration be required?

2) One of the (maybe the strongest) reason for combining the two profiles we discussed was that  health workers consider the mom + baby as one unit during PNC. Thinking another way about it, PNC home visits and PNC health facility visits are usually attached or "assigned" to the mother. The visit just includes checking on the baby as well. We're talking about splitting the rows and profiles, therefore you'd have two rows (in the PNC register list) instead of one and two PNC home visits showing as due in the register list. Health workers don't think of them as separate PNC visits. The PNC visit is mom + baby(ies). Do we feel the advantages of splitting profiles outweighs the perception shift for the health worker?

2a) We have reporting indicators concerning PNC visits as well, so splitting these into two separate visits will have large ramifications for the meaning of completing PNC visits. Do we consider the PNC visit complete if only mom + all babies' PNC visits are complete?

2b) The "PNC health facility visit" is one of the tasks in the PNC home visit. It's currently "assigned" to the mother, and it appears even after the child has shifted to the Child register. The difficulty is that this task contains questions for the child. So with this new approach, in addition to splitting out the profiles, we'd have to probably create a new PNC health facility visit task for the baby and then modify the mother PNC health facility visit task. Essentially, I think it would be a change to the data model and might have repercussions with existing data from the roll-out.

3) Tutorial videos, user guides, etc. All of these are already distributed and we'd be asking UNICEF to make updates to all of these and distribute the updates. They may decide not to make the updates, though.

5) PNC in-app indicators might need to be redone. I talked about one above, but perhaps all of the PNC indicators would need to be redone if there are data model changes. I don't know whether this will be required, though. 

6) We'd have to create a new "newborn" row in the PNC clients register. Instead of mother name, PNC day number, and village, what would it be (mother name, baby name, age, gender, village?)? We've never had two types of rows before in a single register view. Would this be difficult to do?

7) We'd want to link the mom + baby profiles I imagine, similar to in ZEIR, where you could see the siblings linked to that child. That might be new functionality here.

**Comment by rowo** [comment]
@cafootitt Thanks for the list. We should probably discuss in a meeting. From a UX standpoint, we think it's nice (though it's a bit messy) to have all questions in one form (point 2). However it maybe not be a large cost in terms of perception shift to split them up since the form is set up in a way that splits them up (i.e. fields for mom, fields for child), so this change is just about organizing fields a bit more differently.

The main thing we need to prep for a discussion are to roughly estimate how much work the listed items would be... 1, 2a, 2b, 3, 4, 5, 7.

- For 2a, can you submit a PNC visit form if one of the children isn't present? I don't think this changes how we define a complete PNC visit, this would mean we'd have to say the indicator is complete by both mother + child tasks.
- For 5, I think the baby row could be the same as current PNC row except adding a line for the baby name. Age would equal PNC day. Gender is not needed.
- For 7, would the the PNC baby history would be the same as Child history?

**Comment by rowo** [comment]
@cafootitt @msschroeder @mberg anybody take notes on where this left off? Do I need to do anything?

**Comment by msschroeder** [comment]
@rowo @cafootitt @mberg  Major notes from our meeting on multiple children:

Currently, the mother and child are located in one profile. The proposed changes are as noted:

Short term: 
- Add the form changes to allow the registration of multiple babies in the Pregnancy Outcome form using a repeat group. 
- Determine what the profile would look like for a mother with multiple babies
- If there are multiple babies, there will be multiple tasks per baby in the home visit by name as noted above

Long term:
- Change when the child is added to the child register. The child would be added to the child register when born. They will also be added to the child register and family register at this point. 
- Children and PNC women will both be able to access the PNC home visit from their profile
- Change the data model to split the PNC home visit button to appear on both the mother and child and link back to each other (i.e. you can do one, such as the mother, and then flow to the other, such as the child)

**Comment by cafootitt** [comment]
Notes from 19 Nov:

- CF to send current medical history and upcoming services screens to Roger and data dictionary so he can design these two pages
- We'll need to update the following:
-- Repeat group to Preg Outcome form
-- Modify PNC profile to show multiple babies
-- Modify top right dropdown to show Edit Child Under 5 for each baby
-- Modify upcoming services page
-- Modify medical history page
-- Add more tasks for each child in child home visit
-- Remove the colored circle around PNC avatar when there are multiple pages
-- Update business rule so that child gets added early to child register if mom is removed
-- Add Remove child options for each baby in top right menu

**Comment by cafootitt** [comment]
PNC medical history page:
![Screenshot_20191120-093406_CFC-RTM - Guine](https://user-images.githubusercontent.com/3488986/69215299-606ea100-0b7a-11ea-9467-3dac971c1b46.jpg)


PNC upcoming services page has a bug and it's not appearing for any PNC woman, so I can't take a screenshot, but here's the child upcoming services page, which is similarly formatted:
![Screenshot_20191120-094455_CFC-RTM - Guine](https://user-images.githubusercontent.com/3488986/69215361-8bf18b80-0b7a-11ea-97b4-d342f6a8e30a.jpg)

This will also be helpful:
https://docs.google.com/spreadsheets/d/11YsEYAXGr8aQUJm2vOKwTogyqj1XKsPwGboT-aKDpZA/edit#gid=0

It shows the PNC home visit tasks for mother vs. baby and which ones appear in upcoming services and medical history.

**Comment by cafootitt** [comment]
@rowo When can you get mockups to us?

**Comment by rowo** [comment]
By Friday

**Comment by rowo** [comment]
@cafootitt includes Marvel handoff
Upcoming services: https://marvelapp.com/9j1277a/screen/64501183
- Doesn't seem like multiple babies changes this view

History: https://marvelapp.com/9j1277a/screen/64501182
- I opted to organize things by person
