### ISSUE TITLE
[discussion] How to add pregnant woman icon to Family Register page

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-chw-anc#16]
<img width="326" alt="Screen Shot 2019-05-08 at 8 50 03 AM" src="https://user-images.githubusercontent.com/3488986/57352582-7f718c80-716e-11e9-82d3-b0d32574cc55.png">

For ANC, it's straightforward to add the purple pregnant icon to the family row in the family register when the woman becomes pregnant, but what about for PNC? Do we create a new icon for a postpartum woman that would show for the 42 days she's in PNC register? Do we add the child icon as soon as the delivery is recorded or only after 28 days when the child is added to the child register?

**Comment by msschroeder** [comment]
@cagulas @rowo For the PNC, could we use the smaller icon from the register with a mother and child? Or would that be too big or too much detail for that small of an icon? I think for consistency it might be nice, but it is a short period. The same question will come for malaria as well. Also, how will this affect the app as other modules are added having an icon on the Family register?

I think at 28 days the child icon appears, because the mother and child are treated as the same profile until the 28 days when the child moves the child register.

**Comment by cagulas** [comment]
@msschroeder @rowo What was the resolution to this issue? What are the devs implementing?

**Comment by msschroeder** [comment]
@cagulas There were no decisions on this. @rowo What are your thoughts?

**Comment by rowo** [comment]
The icons can either represent the people in a family or it can represent membership in registers. I know I've been thinking about it as the latter. Megan's malaria comment also follows that line of thought. In that case, since PNC is a mother-child unit it probably makes sense to do a combination icon where a child isn't added yet.

**Comment by msschroeder** [comment]
@rowo @cagulas That makes sense. So are we going to say that when you are added to any register moving forward - no matter for how long - you will have an icon added to the all family register?

**Comment by cagulas** [comment]
I've attempted to type up the rules for the icons. Please feel free to correct/edit.

Rules:

- Pregnant woman icon for each record in the ANC register (start: ANC Registration; end: Pregnancy outcome)
- Postpartum icon (woman + baby) for each record in the PNC register* (start: Pregnancy outcome of live or stillbirth only; end: End of postpartum period, i.e. 42 days)
- Child icon (pink or blue depending on gender) for each record in the Child register** (start: Either end of neonatal period (28 days) when child record gets created separately from the PNC record OR Child U5 Registration; end: Child reaches 5 years of age)
- Mosquito icon for each record in the Malaria register (start/end: @msschroeder pls fill this in)

NB: For all of the icons above, if the person's record is closed via the close family member or close U5 child form, the icon no longer appears as well. This is a rule across the board.

NB: start/end refer to when the icon appears and no longer appears on the family record in the family register.

*The slight problem is that in the event of a stillbirth, the woman would show up in the PNC register without the child, so it's a little inappropriate to represent her PNC record as a mother/baby icon, but I can't think of an obvious or elegant solution for this.
**Slight problem whereby the child icon gets added, but the PNC icon remains, since the woman remains in the PNC register longer than the child. This could wrongly be construed as an extra child in the household, but again, don't see an obvious solution for this.

**Comment by cagulas** [comment]
@rowo Can you think of a solution for either of the two problems I noted above? Or @msschroeder ?

**Comment by msschroeder** [comment]
@cagulas @rowo Could we do PNC as just a woman - not a mother or child? I think this would account for both problems noted above?

**Comment by cagulas** [comment]
Decision: The rules above were discussed and finalized. @msschroeder will simplify the malaria rules logic.
