### ISSUE TITLE
Create graphics for danger signs set

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#17]
In the [data dictionary](https://docs.google.com/spreadsheets/d/1hZrD3P8X3YAd-JvlXdT4TGKWJ87NlaLKjJlPrJZFwMY/edit#gid=102133992), ANC Home Visit tab, we need graphics for the danger signs set that's included there:

Fever
Bleeding vaginally
Severe headache
Convulsions
Difficulty breathing
Severe abdominal pain
Swollen face and legs

Since adding these graphics to the page itself will likely make it too long, do you suggest we put this in an info icon that they can click to view the full danger sign graphics if needed.

Danger sign graphics sent by Ngozi over email. And attaching here as well.

[08. Danger sign Women.pdf](https://github.com/OpenSRP/opensrp-client-chw-anc/files/3151399/08.Danger.sign.Women.pdf)

Please update this issue (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/18) with the assets when complete.

------------------------------------------------------------------------------------------------------
 **BA is slightly different**: There are additional danger signs:

**Same:** Fever
**Same:** Bleeding vaginally
**Same:** Severe headache
**Same:** Convulsions
**Same:** Difficulty breathing
**Same:** Severe abdominal pain
**Different:** Swelling of the face and/or hands
**Different:** Discoloured or watery, liquid vaginal discharge with a bad smell
**Different:** No movement / unusual movement for a child in the womb
 
Since there are additional danger signs, @rowo @cagulas should we include the icons for BA? If so, where would you recommend we get the icons from? We can maybe ask Jphiego if they would like to include the icons?

In the [data dictionary](https://docs.google.com/spreadsheets/d/1feKFVFtCZsGVzwEglbDZ4f5uP84F8wL2jwwXvfqUgP0/edit?usp=sharing), CHW 2 - ANC HH Visit

**Comment by rowo** [comment]
@cagulas Do these images need to be individually sliced up assets or a single long asset/image?

**Comment by cagulas** [comment]
Hm, good question. I guess only a single long asset, but if any of them get updated, that might make it difficult to swap one out, right?

**Comment by rowo** [comment]
For me, just editing an image, it will be easy either way

**Comment by cagulas** [comment]
Ok, cool. I guess just one long asset then.

**Comment by cagulas** [comment]
@rowo When can we get this from you? We need to urgently wrap up all ANC issues now.

**Comment by rowo** [comment]
@cagulas Is there a way you can request the remaining "difficulty breathing" graphic from them? I don't see how we should be responsible for creating a graphic that matches. We should only invest a small amount of time on this i.e. do something much simpler.

@msschroeder Just because we have the asset doesn't give Jhpiego permission to use UNICEF's intellectual property. They'll have to provide their own content or they should work out a way to use UNICEF or someone else's stuff.

Doing custom illustrations is a grey area in our contracts. For the future, we should be sure to note that any custom illustrations done are not included in the contract and require the client to provide if they want this stuff. We can't be put into a situation where the client determines that all questions would be better with visuals and then just expect us to make it and have them own property rights in perpetuity. That's not right and wouldn't really fly anywhere.

**Comment by msschroeder** [comment]
@rowo Cool. Thanks for the clarification. I will check with Jphiego and see if they would like to include any icons in this section and have icons available.

**Comment by cagulas** [comment]
@rowo Cool, I must have missed that that one was missing. Maybe they added it separately. They might not have one for it then, and I agree we're not responsible for creating one.

As for your other points, I agree we need to find a solution for this. Usually we handle this by adding a few days of "design time" for you in a contract. Can we bring this up on the project coordination or biz dev call to see if anyone else on the team has a process for this, and if not, we can co-create one?

**Comment by rowo** [comment]
@cagulas Yes, that makes sense for the biz dev call, I will mention it. This is a rights issue because as an illustrator, I would never charge just my billable time for unlimited rights to illustrations in perpetuity. If you think about it like a song or commercial jingle, or really even a logo it wouldn't be fair. For something like this or like those West Africa home visit drawings, we might want to give rights to any OpenSRP implementation (or Ona) to use something else.

**Comment by rowo** [comment]
Here are the images so far. Is this what you are thinking, with the labels?

![danger-signs](https://user-images.githubusercontent.com/1584163/58898436-91404400-86c8-11e9-95ea-6c3bd2a3adce.png)

**Comment by cagulas** [comment]
@rowo Cool, thank you. I think the labels are fine to keep. They mostly match the labels in the form.

**Comment by cagulas** [comment]
@msschroeder Changing this to BA-specific issue now and leaving open.

**Comment by msschroeder** [comment]
@cafootitt @rowo We will not be using icons for the BA instance, unless the client decides to later, but there has been no mention from the client to this point. So I will close the issue.
