### ISSUE TITLE
Remove "other phone number" field from ANC Registration form

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#199]
I noticed this field appeared in the ANC registration form. Not sure where it came from, but this isn't a part of the data dictionary, so it needs to be removed. This is true for all 5 west africa countries.

![Screenshot_20190807-124104](https://user-images.githubusercontent.com/3488986/62472753-110d8c00-b7a8-11e9-9cfb-28c39b07d63f.png)

@msschroeder Did this show up in your form as well?

**Comment by ellykits** [comment]
This is for WCARO but the fix is done for all the West Africa flavors

![Screenshot_1567170142](https://user-images.githubusercontent.com/26865532/64022810-a994f300-cb3f-11e9-8289-40178301310f.png)
![Screenshot_1567170171](https://user-images.githubusercontent.com/26865532/64022811-a994f300-cb3f-11e9-9382-3cb9a6e6ef91.png)

**Comment by cafootitt** [comment]
Perfect / Parfait

**Comment by cafootitt** [comment]
31 Aug release - lgtm
