### ISSUE TITLE
[Discussion] What should family due button show when multiple types of visits are due?

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#2]
This has come up now that we are ready to start implementing multiple registers in the same app. Before, only a child home visit was a possible due task for a family, but now that we are adding ANC, malaria, etc., the types of tasks now range from child home visit, to anc home visit, to pnc home visit, to malaria follow-up, referral follow-up, etc. The question is how do we summarize this information in a single due button for the family in the family register list? The constraint is obviously space. We cannot show everything that's due because we don't have the space to, so how do we summarize what needs to be done?

The simplest this is just to show whether or not (someone in) the family needs to be visited. For them to see who and why, they'd have to tap on the button, where it would direct them to the "Due" tab in the family profile view where they can see what tasks need to be done. This is probably the simplest to implement. We'd have to figure out what labels to use on that button though, e.g. Visit(s) due, Visit(s) overdue, Task(s) due, Task(s) overdue, etc.

More complicated would be to show the number of tasks or the number of people to be visited. Most of the time number of tasks = number of people needs to be visited, but an edge case might be where a person has both a visit due and a malaria or other referral follow-up due, so we'd have to make a decision which to show (# people vs. # tasks).

Let's have a discussion to finalize this here.

**Comment by rowo** [comment]
This isn't an entirely new problem to OpenSRP. The first thing you mentioned is an existing Reveal solution that has agreement from the client (though it hasn't been piloted). The use case is a bit more contained since it's kind of like a short term (1 day to 1 week) to do list for focus investigations, which involve multiple interventions at households. What we've done there is to assign colors to phases (which apply to both map and register list views): 
<img width="366" alt="Screen Shot 2019-04-20 at 11 18 48 AM" src="https://user-images.githubusercontent.com/1584163/56459199-18766a00-635e-11e9-833d-1b4bdb8132b9.png">

The second item is something I started working on with Xi last Fall in anticipation of this issue. We put number of tasks in the "due" column and used the overdue status color of the most due task. We always thought about it as number of tasks to be done — I don't think number of people ever came up in our discussions. Tasks makes most sense to me because number of people to see would not match up directly with any number shown on the family profile view.
<img width="252" alt="Screen Shot 2019-04-20 at 11 31 23 AM" src="https://user-images.githubusercontent.com/1584163/56459320-d9491880-635f-11e9-9693-b2c5d92faeb1.png">

Another direction I've seen is to show only the most overdue item. I think this is how it was in Dristhi. This is how v1 of the immunization history was treated, https://github.com/OpenSRP/opensrp-client-chw/issues/142, though it was changed.

**Comment by msschroeder** [comment]
@cagulas @rowo For this, I would probably think more about the number of people I would have to see rather than the number of tasks. As a CHW, I would think that you would think more about the number of people you need to visit per household than the number of tasks in the household. But, I think in other use cases, like Reveal, the tasks might make more sense as it is a very task focused app. Also, there could be more tasks than people with malaria. 

I also think I prefer to show the number of tasks/people to visit with a visit required vs. the most overdue task because I think it most a number of households will have more than one task/person to visit.

**Comment by rowo** [comment]
To me, the number is not a big deal since most of the time tasks and people will match — plus I don't see the difference between 2 and 3 tasks or people changing what a user does because it's not clear what is more important. A red "4" could mean 1 overdue plus 3 due people, or it could mean 1 person with 4 overdue items. You don't know until you tap in to review and you can't really tell importance because since the tasks or people will have varying risk levels.

So really my goal with the UI is just to avoid confusion, which is why matching up number to something specific in the family profile is cleanest to me. Otherwise, if we were doing people, I'd maybe try to redesign the task tab in the family profile so it makes more sense (organized by person and not by chronological due for instance).

**Comment by cagulas** [comment]
Makes sense to me.

**Comment by msschroeder** [comment]
I agree.

**Comment by cagulas** [comment]
Ok, so the decision is to show the number of tasks, not people, because it will match the number of tasks shown in the "Due" tab in the family profile view.

**Comment by rowo** [comment]
Two related items: 
- Does showing number only apply when multiple tasks are due? For example if only a home visit is due, would we only show "visit due" or would we should "1"? 
- Does this rule also apply to individual client registers such as ANC + malaria?

**Comment by cagulas** [comment]
@rowo For 1, since we have tasks that are not home visits (i.e. malaria follow-up), maybe just the number is better to show? I'm a bit ambivalent about it, though. And technically a malaria follow-up is a visit still.

For 2, I can't rule it out, but I don't have an example for you, either.

**Comment by cagulas** [comment]
@rowo @msschroeder Did you both reach a conclusion on this while I was on leave?

**Comment by msschroeder** [comment]
@cagulas @rowo I thought this was closed. I got that we were using numbers.

**Comment by rowo** [comment]
@cagulas We didn't discuss this when you were out.
- We are agreed about using total tasks due for the family.
- For the case of a single item due, I think we can just show 1 unless there are objections.
- For number 2, I don't think this will happen.

**Comment by msschroeder** [comment]
@rowo I think it will be a little confusing to just have a number. I think like a little text like "1 Task", 3 Tasks, etc. is a little easier to understand. What are your thoughts on this @cagulas @rowo?

**Comment by cagulas** [comment]
I think the number only is fine. Should we increase the font size for health workers working outdoors? I think the small number might be difficult to see for some. This is also something that should be heavily covered in training, so I'm less concerned about the meaning of the number to health workers. 

We are introducing the term "task", though, which I'm wondering how that will go over with the health workers. I can send this to our client and to ask for feedback.

There is also the "not done" status. Refer to this issue for reference on the rules: https://github.com/OpenSRP/opensrp-client-chw/issues/14.

I guess it would say, to follow this scheme, "Tasks not done".

**Comment by rowo** [comment]
Sizing up the number or making it medium weight is okay. I can look at that. If what works in the currently built app is fine, I don't know if it needs to change just because it's a single character.

True, "task" being new presents an unknown... other alternatives could be Services. Or maybe "due tasks", "due items" to match profile wording. But leaving up to client is okay too.

**Comment by cagulas** [comment]
Waiting on feedback from the client.

**Comment by msschroeder** [comment]
@cafootitt @rowo I am assuming we will want to apply whatever we do here to Malaria as well. But if we are getting feedback from the client on this as well - would we also want to check with Jphiego and see what their thoughts are too. My worry is this feedback will take a very long time to get back from them.

**Comment by cafootitt** [comment]
@msschroeder I have yet to hear back, so let's proceed with what we've agreed to internally. Would you be able to take a stab at writing up the implementation issue for this?

**Comment by msschroeder** [comment]
Closing issue and created #72
