### ISSUE TITLE
Add ANC Registration button to WRA profiles

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-chw-anc#3]
When a family head or family member is registered, we have a field in both forms to calculate whether or not that person is a woman of reproductive age (WRA): `wra`

For these profiles, we need to add a button to the top right dropdown in that person's profile to allow them to be registered in the ANC register. This will be the only possible entry point to the ANC register.

Label for the button: ANC Registration
Add this option in between Registration info and Remove this person.

![Screenshot_20190419-161828](https://user-images.githubusercontent.com/3488986/56426090-92a3e180-62bf-11e9-9b27-d0aa39bddfc7.png)

Tapping on this button opens the ANC registration form.

------------------------------------------------------------------------------------------------------
BA: No changes. It should be applied the same to BA

**Comment by rkodev** [comment]
@msschroeder @cagulas @manutarus after registration of users into the ANC register, should we disable this button?

**Comment by msschroeder** [comment]
@rkodev Yes, once the user is registered to ANC, this specific function should be disabled and replaced with the the drop down from the ANC profile (#32 ). This form is essentially transitioning the person from an WRA to an ANC profile. So they will have different drop downs menus
@rowo  Does that sound okay to you as well - I would value another opinion with Carolyn away.

**Comment by cagulas** [comment]
lgtm

**Comment by rowo** [comment]
@msschroeder Question, are we doing a FAB or a top right pull down for these forms in BA?

**Comment by msschroeder** [comment]
@rowo We are doing the same thing as WCARO, which I believe is the top right pull down. We are trying to be consistent on WCARO and BA.

**Comment by rowo** [comment]
@msschroeder This is late, but yes, the requirement from that BA profiles doc implied this, though I can see how it can be confusing as unconnected issues.

For these kind of issues that require a level of logic above them, I can see it being helpful to have a brief parent issue that references all of the children issues and spec out the logic/behavior. I'm not sure if the engineers preferred the above issue approach though (since we talked about taking the time of PMs and engineers creating issues together), but I can see it being helpful for a complete understanding.
