### ISSUE TITLE
Constrain the BCG and OPV 0 fields in Pregnancy Outcome to the delivery date

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#303]
In the Preg Outcome form, the BCG and OPV 0 fields should have a constraint where they cannot be before the delivery date, i.e.

`opv0_date` and `bcg_date` must be `>= {delivery_date} and <= {today}`

**Comment by allan-allay** [comment]
Attempted 2 approaches in constraining these dates:
- Can be done in the forms themselves by a legacy approach "constraints": [{ "type": "date", "ex": "lessThanEqualTo(., step1:numbers_selector)" }]
- And a constraints-rules file
These approaches work in that they show the appropriate error message but they don't prevent form submission with an invalid date. 
To constrain the date selection so that selectable values are the >= delivery date it is possible to set the min_date as the delivery date but the caveat is that the delivery date can't be selected. 
To get this working, it has to be inbuilt into native forms date picker to support passing the min_date expression as step1_delivery_date-1d

**Comment by allan-allay** [comment]
I added constraints for the BCG and OPV 0 dates, but when the constraint is violated, an error message is displayed but the form can still be submitted. 
Prevention of submission is to be handled in this separate native forms issue -> https://github.com/OpenSRP/opensrp-client-native-form/issues/277

**Comment by cafootitt** [comment]
V1.0.6

lgtm
