### ISSUE TITLE
Exclusive breastfeeding task in PNC is not working correctly

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-anc#332]
- [x] When No is select, No should appear in the underneath text for the completed task
- [x] When Yes is select, Yes should appear in the underneath text for the completed task

Currently, the opposite is happening - When I select No or Yes, the opposite appears Yes or No, respectively

To replicate,
1. Do a PNC home visit 
2. Select Yes in exclusive breastfeeding
3. Save
4. Text appears No and Yellow task coloring - The opposite should occur

**Comment by cafootitt** [comment]
@paulinembabu Might make sense to pick up this issue as you work on https://github.com/OpenSRP/opensrp-client-chw-anc/issues/308.

Note that WCARO and BA are opposite, due to the way the question is phrased. 

In WCARO, answering No means they are exclusively breastfeeding, while answering Yes means they are not exclusively breastfeeding. BA is the opposite.

**Comment by msschroeder** [comment]
lgtm
