### ISSUE TITLE
Update the pregnancy outcome form to allow multiple babies to be entered

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-anc#393]
**WCARO**
- [x] Add the question {no_children} to the pregnancy outcome form. This question will determine how many repeat groups are needed for the "Baby Details" questions (see rows 17-18 in Preg Outcome tab in WCARO [data dictionary](https://docs.google.com/spreadsheets/d/1hZrD3P8X3YAd-JvlXdT4TGKWJ87NlaLKjJlPrJZFwMY/edit#gid=1766139480))
- [x] Change the "Baby Details" questions to a repeat group structure.
- [x] For each group, the heading should be "Baby #N Details", where N is the iteration of the total number of babies entered 

NOTE: How will this affect the data that has already been entered?

----------------------------------------------------------------------------------------------
**BA**
SAME - Data dictionary: https://docs.google.com/spreadsheets/d/1feKFVFtCZsGVzwEglbDZ4f5uP84F8wL2jwwXvfqUgP0/edit?usp=sharing - Tab CHW 4 - Pregnancy Outcome - Multiple Births
- [x] Remove/hide the no_children question (highlighted in pink)
- [x] Add the question {no_children_no} (highlighted in light blue)

**Comment by cafootitt** [comment]
WCARO QA on 3 Feb:

- [ ] Not working at all in the French version of the form. The repeat group field does not appear.
- [ ] Number of children born should have the following constraint on it: . > 0 and < 10
- [ ] `essential_newborn_care` field is missing from the baby repeat groups. See row 39 in data dictionary, Pregnancy Outcome tab.
- [ ] If you change the number of children born field, you cannot submit the form, because a message pops up that you have 55 errors in the form. To replicate, open preg outcome form, then enter live birth result and enter 3 children born, then change it to 11 children born, then change it to 0 children born, then back to 3. Fill in the form with details for the 3 children and try to submit. The error pops up.

**Comment by msschroeder** [comment]
BA QA Jan 31 Build:
- [ ] Not working at all in the Swahili version of the form. The repeat group field does not appear.
- [ ] **Please add to BA too:** Number of children born should have the following constraint on it: . > 0 and < 10
- [ ] **Not working on BA too:** If you change the number of children born field, you cannot submit the form, because a message pops up that you have 55 errors in the form. To replicate, open preg outcome form, then enter live birth result and enter 3 children born, then change it to 11 children born, then change it to 0 children born, then back to 3. Fill in the form with details for the 3 children and try to submit. The error pops up.

**Comment by cafootitt** [comment]
@manutarus Can we urgently work on this issue? I think it might have been lost in the to do column, but of all the multiple baby QA fixes, this is probably the most important to address.

**Comment by msschroeder** [comment]
QA Build Feb 17:
- [ ] Not working at all in the Swahili version of the form. The repeat group field does not appear.
- [ ] **Please add to BA too:** Number of children born should have the following constraint on it: . > 0 and < 10

**Comment by cafootitt** [comment]
Wcaro - lgtm - good work!

**Comment by msschroeder** [comment]
BA - Lgtm too! Thanks everyone!
